AWSTemplateFormatVersion: '2010-09-09'
Description: API Gateway and Lambda
Parameters:
  WorkshopName:
      Type: String
      Description: Project Name
  BucketName:
      Type: String
      Description: Bucket that contains Lambda zip file
  ZipfileName:
      Type: String
      Description: Zip file name that contains Lambda function code
Resources:
  S3BucketImages:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Sub "property-images-hd-${WorkshopName}"
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
      - PolicyName: LambdaServiceRolePolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - s3:Get*
            - s3:List*
            Resource: arn:aws:s3:*:*:*
  APIServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - apigateway.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
      Policies:
      - PolicyName: APIGatewayServiceRolePolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - lambda:InvokeFunction
            Resource: !GetAtt APIFunction.Arn
  APIFunction: 
    Type: AWS::Lambda::Function
    Properties: 
      Code: 
        S3Bucket: !Ref BucketName
        S3Key: !Ref ZipfileName
      FunctionName: !Ref FunctionName
      Handler: Get_Image.get_image
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.8
      Timeout: 60
      MemorySize: 1024
  Version:
    Type: AWS::Lambda::Version
    Properties: 
      FunctionName: !Ref APIFunction
      Description: v1
  RestAPI: 
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: API to get Property Image
      Name: Get_Property_Image API
      EndpointConfiguration: 
        Types: 
        - REGIONAL


